$(function(){
var str = '<div class="footer mt40">'
			+'<div class="wrap clearfix">'
		    +'<dl>'
			+'<dt>新手帮助</dt>'
			+'<dd>'
			+'<ul>'
			+'<li><a href="help/basicconcept.html" target="_blank">基本概念</a></li>'
			+'<li><a href="help/type.html" target="_blank">基金类型</a></li>'
			+'<li><a href="help/account.html" target="_blank">账户中心</a></li>'
			+'<li><a href="help/transaction.html" target="_blank">交易指南</a></li>'
			+'</ul>'
			+'<dd>'
		    +'</dl>'
			+'<dl>'
			+'<dt>安全保障</dt>'
			+'<dd>'
			+'<ul>'
			+'<li><a href="safe/risktip.html" target="_blank">风险提示</a></li>'
			+'<li><a href="safe/disclaimers.html" target="_blank">免责条款</a></li>'
			+'<li><a href="safe/safeguide.html" target="_blank">安全指引</a></li>'
			+'<li><a href="safe/investorright.html">投资人权益须知</a></li>'
			+'</ul>'
			+'<dd>'
			+'</dl>'
			+'<dl class="bor">'
			+'<dt>关于我们</dt>'
			+'<dd>'
			+'<ul>'
			+'<li><a href="us/index.html" target="_blank">关于我们</a></li>'
			+'<li><a href="us/index.html?type=1" target="_blank">合作伙伴</a></li>'
			+'<li><a href="us/index.html?type=2" target="_blank">加入我们</a></li>'
			+'<li><a href="us/index.html?type=3" target="_blank">联系我们</a></li>'
			+'</ul>'
			+'<dd>'
			+'</dl>'
			+'<div class="foot-mob">'
			+'<ul class="foot-title clearfix">'
			+'<li><i class="abs abs-line2px"></i>'
			+'<h2 class="h2">移动客户端下载</h2>'
			+'</li>'
			+'</ul>'
			+'<div class="foot-cont"><img src="images/2wm/root_app.jpg"><a href="javascript:;"><i class="ico ico-android"></i>'
	        +'<h4 class="h4">下载</h4>'
	        +'</a><a href="javascript:;"><i class="ico ico-ios"></i>'
	        +'<h4 class="h4">下载</h4>'
	       	+' </a></div>'
			+'</div>'
			+'<div class="foot-sns">'
			+'<ul class="foot-title clearfix">'
			+'<li><i class="abs abs-line2px"></i>'
			+'<h2 class="h2">大仓基金微信</h2>'
			+'</li>'
			+'</ul>'
			+'<div class="foot-cont"><img src="images/2wm/root_weixin.jpg"> <span class="first">微信号</span> <span>dacang</span></div>'
			+'</div>'
			+'</div>'
			+'<div class="wrap">'
			+'<div class="foot-tips"><span class="abs">基金投资需谨慎</span></div>'
			+'<div class="foot-copy">Copyright &copy; 2015 上海慧点投资管理有限公司 版权所有 沪ICP备15029296号</div>'
			+'</div>'
		    +'</div>'
		$("#bottom").append(str);
})