$(function(){
var str = '<div class="m-topbar">'
			  +'<div class="wrap clearfix">'
			  +'<div class="telbox rel"><i class="ico ico-stel"></i><em class="ft-nums fl">4000-383-111</em><span class="fl">（工作时间 9:00 - 19:00）</span></div>'
			  +'<div class="top-nav">'
			  +'<ul>'
			  +'<li><a href="../login.html" class="hi" target="_blank">请登录</a></li>'
			  +'<li class="c-grayccc">｜</li>'
			  +'<li><a href="../register.html" class="hi" target="_blank">免费注册</a></li>'
			  +'<li class="c-grayccc">｜</li>'
			  +'<li><a href="javascript:;" class="aphone"><i class="ico ico-sphone"></i>手机客户端</a></li>'
			  +'<li class="c-grayccc">｜</li>'
			  +'<li><a href="../safe/index.html" target="_blank">安全保障</a></li>'
			  +'<li class="c-grayccc">｜</li>'
			  +'<li><a href="../help/index.html" target="_blank">帮助中心</a></li>'
			  +'<li class="c-grayccc">｜</li>'
			  +'<li><a href="../us/index.html" target="_blank">关于我们</a></li>'
			  +'</ul>'
			  +'</div>'
			  +'</div>'
			  +'</div>'
			  +'<div class="head">'
			  +'<div class="wrap clearfix">'
			  +'<div class="logo"><a href="../default.html"><img src="../images/logo.png" /></a></div>'
			  +'<div class="head-nav fl">'
			  +'<ul>'
			  +'<li class="active"><a href="../default.html">首页</a></li>'
			  +'<li><a href="../super.html">超级现金宝</a></li>'
			  +'<li><a href="../newhand/guide.html">新手专区</a></li>'
			  +'<li><a href="../market/buyfund.html">基金选购</a></li>'
			  +'<li><a href="../top/general.html">收益排行</a></li>'
			  +'<li><a href="../news/news.html">资讯</a></li>'
			  +'</ul>'
			  +'</div>'
			  +'<div class="userinfo fr"><a href="../member/myaccounts.html" target="_blank"><img class="vis" src="../images/man.png"><img class="hid" src="../images/redman.png"></a></div>'
			  +'</div>'
			  +'</div>';
		$("#top").append(str);
})